// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZFbK7hIU56fV105gY74-6fRks8y64eUU',
    appId: '1:932243276700:web:2ed8dfa11e68541658fe59',
    messagingSenderId: '932243276700',
    projectId: 'smilehub-1c44a',
    authDomain: 'smilehub-1c44a.firebaseapp.com',
    storageBucket: 'smilehub-1c44a.firebasestorage.app',
    measurementId: 'G-WE9PYJCXXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPPPi-oQElzk9CBBeDf-I_xpCJ2DIDSl4',
    appId: '1:932243276700:android:c3dfb32e2751870458fe59',
    messagingSenderId: '932243276700',
    projectId: 'smilehub-1c44a',
    storageBucket: 'smilehub-1c44a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZFbK7hIU56fV105gY74-6fRks8y64eUU',
    appId: '1:932243276700:web:fa3e6a329a4cff4858fe59',
    messagingSenderId: '932243276700',
    projectId: 'smilehub-1c44a',
    authDomain: 'smilehub-1c44a.firebaseapp.com',
    storageBucket: 'smilehub-1c44a.firebasestorage.app',
    measurementId: 'G-P09GBVHHBP',
  );
}
